adding link to duckdb docs
Mause/duckdb_engine pull request #560
Opened 2023-02-28 09:31 UTC by edublancas

Hi! I added a link to DuckDB's docs to the README (which uses JupySQL 😁). Let me know what you think!

2023-02-28 10:04 UTC, Mause requested changes

2023-02-28 10:04 UTC, Mause commented on README.md
> +Alex Monahan great demo of this on [his blog](https://alex-monahan.github.io/2021/08/22/Python_and_SQL_Better_Together.html#an-example-workflow-with-duckdb).
```suggestion
Alex Monahan's great demo of this on [his blog](https://alex-monahan.github.io/2021/08/22/Python_and_SQL_Better_Together.html#an-example-workflow-with-duckdb).
```

2023-02-28 10:28 UTC, Mause commented
@edublancas are you able to fix up the commit message and the grammar? Happy to merge once that's done

2023-02-28 18:50 UTC, edublancas commented
looks like the commit name is good now :)

2023-03-01 03:58 UTC, Mause commented
Thanks!

2023-03-01 03:58 UTC, merged

2023-03-01 04:14 UTC, edublancas commented
woohoo 🎉