Allow passing parameters in connection string
Mause/duckdb_engine pull request #675
Opened 2023-06-02 19:41 UTC by elefeint

Currently the only way to pass settings to DuckDB is through the `connect_args` parameter. 

This PR allows URL parameters in the connection string [parsed by SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy/blob/14825668ab407115f793dd229ed694c5c607c657/lib/sqlalchemy/engine/create.py#L548) to get passed back to the framework from this driver's `create_connect_args()` function. I did something similar to SQLAlchemy's [reference implementation](https://github.com/sqlalchemy/sqlalchemy/blob/14825668ab407115f793dd229ed694c5c607c657/lib/sqlalchemy/engine/interfaces.py#L1233-L1236), but allowing for config mutability since it will get split into core and extended properties in `connect()` method.

Affiliation: MotherDuck

2023-06-13 17:31 UTC, Mause commented
Hi @elefeint, can you explain why you want this? Are you using an application that doesn't allow you to specify connect_args?

Also, I'd appreciate it you could find the time to fix the various ci failures and warnings

2023-06-14 04:41 UTC, elefeint commented
@Mause Sorry for the failures! 

The reason for the PR is that when troubleshooting something unrelated, I noticed that connection string parameters behaved differently than `connect_args` - they got ignored. This would pause no difficulty to users accessing DuckDB through SQLAlchemy programmatically, since they can use `connect_args`, but for users of 3rd party integrations built on top of SQLAlchemy such as [Superset](https://superset.apache.org/docs/databases/installing-database-drivers/), the connection string is often the only settable configuration the user has access to.

This isn't blocking anything I am currently working on, but it seemed like a nice harmless improvement... until my lack of Python knowledge caught up with me...

2023-06-14 07:32 UTC, Mause requested changes

2023-06-14 07:32 UTC, Mause commented on duckdb_engine/tests/test_basic.py
> +            text("select value from duckdb_settings() where name='worker_threads'")
```suggestion
            text("select current_setting('worker_threads')")
```

2023-06-14 07:32 UTC, Mause commented on duckdb_engine/tests/test_basic.py
> +    eng = create_engine("duckdb:///:memory:?worker_threads=123")
Could you add a test that uses both config_args and query parameters?

2023-06-19 12:02 UTC, elefeint commented
Sorry, I was at a conference last week. Thank you for fixing this PR up!
Is there something else I can do on this?

2023-06-19 16:31 UTC, merged